export const TOPIC_ID_EMPTY = 'TOPIC_ID:EMPTY';
export const TOPIC_ID_SUCCESS = 'TOPIC_ID:SUCCESS';
export const LOCATION_ID_EMPTY = 'LOCATION_ID:EMPTY';
export const LOCATION_ID_SUCCESS = 'LOCATION_ID:SUCCESS';
export const ALGORITHM_EMPTY = 'ALGORITHM:EMPTY';
export const ALGORITHM_SUCCESS = 'ALGORITHM:SUCCESS';

export const SERVICES_EMPTY = 'SERVICES:EMPTY';
export const SERVICES_LOADING = 'SERVICES:LOADING';
export const SERVICES_ERROR = 'SERVICES:ERROR';
export const SERVICES_SUCCESS = 'SERVICES:SUCCESS';

export const ALGORITHMS_EMPTY = 'ALGORITHMS:EMPTY';
export const ALGORITHMS_LOADING = 'ALGORITHMS:LOADING';
export const ALGORITHMS_ERROR = 'ALGORITHMS:ERROR';
export const ALGORITHMS_SUCCESS = 'ALGORITHMS:SUCCESS';

export const LOCATIONS_EMPTY = 'LOCATIONS:EMPTY';
export const LOCATIONS_LOADING = 'LOCATIONS:LOADING';
export const LOCATIONS_ERROR = 'LOCATIONS:ERROR';
export const LOCATIONS_SUCCESS = 'LOCATIONS:SUCCESS';

export const TOPICS_EMPTY = 'TOPICS:EMPTY';
export const TOPICS_LOADING = 'TOPICS:LOADING';
export const TOPICS_ERROR = 'TOPICS:ERROR';
export const TOPICS_SUCCESS = 'TOPICS:SUCCESS';

export const LOCATION_EMPTY = 'LOCATION:EMPTY';
export const LOCATION = 'LOCATION';
export const TOPIC_EMPTY = 'TOPIC:EMPTY';
export const TOPIC = 'TOPIC';

export const LOCATIONS_COLLECTION_EMPTY = 'LOCATIONS_COLLECTION:EMPTY';
export const LOCATIONS_COLLECTION_SUCCESS = 'LOCATIONS_COLLECTION:SUCCESS';
export const TOPICS_COLLECTION_EMPTY = 'TOPICS_COLLECTION:EMPTY';
export const TOPICS_COLLECTION_SUCCESS = 'TOPICS_COLLECTION:SUCCESS';